import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { digest, finalPageText, validateHumanizerReview, validateSaplingResponse, runEditorialPreflight, privatePath, writePrivateJson } from './editorial-preflight.mjs';
const html = '<html lang="en"><head><title>Title</title><meta content="Metadata" name="description"></head><body><h1>Title</h1><p>' + 'Useful complete article text. '.repeat(30) + '</p><img alt="Caption"><script>privateScript()</script></body></html>';
const text = finalPageText(html);
const review = { text_sha256: digest(text), completed: true, facts_preserved: true, unsupported_claims_removed: true, natural_language_pass: true, second_read: true, reviewer: 'Editorial review fixture', reviewed_at: '2026-10-01T00:00:00Z' };
test('full text includes title, metadata, body, captions but not script', () => { assert.match(text, /Metadata/); assert.match(text, /Caption/); assert.doesNotMatch(text, /privateScript/); });
test('any final prose or caption change invalidates the review', () => { assert.throws(() => validateHumanizerReview(review, digest(finalPageText(html.replace('Caption','New caption'))))); });
test('only finite document score within inclusive owner threshold passes', () => { for (const score of [undefined,null,'0.01',NaN,Infinity,-0.01,0.10001,1]) assert.throws(() => validateSaplingResponse({score,text},text)); for (const score of [0,0.10]) assert.equal(validateSaplingResponse({score,text},text),score); assert.throws(() => validateSaplingResponse({score:0.01,text:'truncated'},text)); });
test('missing provider access makes no network request', async () => { await assert.rejects(runEditorialPreflight({html,review,state:{attempts:[]},saveState(){},fetchImpl(){assert.fail('network')}}), /credential/); });
test('authentic response is requested once with full text and private attempts persisted first', async () => { const state={attempts:[]}; let saved=false; const result=await runEditorialPreflight({html,review,apiKey:'fixture',state,saveState(){saved=true;},fetchImpl:async (url,options)=>{ assert.equal(saved,true); assert.equal(JSON.parse(options.body).text,text); assert.equal(options.redirect,'error'); return {ok:true,json:async()=>({score:0.10,text})}; }}); assert.equal(result.score,0.10); assert.equal(result.release_authorized,false); assert.equal(state.attempts.length,1); await assert.rejects(runEditorialPreflight({html,review,apiKey:'fixture',state,saveState(){}}),/unchanged/); });
test('three attempts maximum; provider failure never returns approval', async () => { await assert.rejects(runEditorialPreflight({html,review,apiKey:'fixture',state:{attempts:[{},{},{}]},saveState(){}}), /three scans/); const state={attempts:[]}; await assert.rejects(runEditorialPreflight({html,review,apiKey:'fixture',state,saveState(){},fetchImpl:async()=>({ok:false,status:429})}),/HTTP 429/); assert.equal(state.attempts.length,1); });

test('private paths resolve symlink parents and reject repository destinations',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'izem-private-test-'));try{const repo=path.join(dir,'repo');fs.mkdirSync(repo);fs.symlinkSync(repo,path.join(dir,'alias'));assert.throws(()=>privatePath(path.join(dir,'alias','result.json'),repo),/outside/);const file=path.join(dir,'result.json');fs.writeFileSync(file,'old',{mode:0o644});writePrivateJson(file,{ok:true});assert.equal(fs.statSync(file).mode&0o777,0o600);fs.symlinkSync(file,path.join(dir,'result-link'));assert.throws(()=>privatePath(path.join(dir,'result-link'),repo),/symbolic/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('public fallback and structured-data prose are included; non-English pages hold',()=>{const page=html.replace('</body>','<noscript><p>Fallback prose</p></noscript><script type="application/ld+json">{"@type":"Article","description":"Schema prose"}</script></body>');const full=finalPageText(page);assert.match(full,/Fallback prose/);assert.match(full,/Schema prose/);assert.throws(()=>finalPageText(page.replace('lang="en"','lang="fr"')),/English/);});
