import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {recoverRequestedNarration, safeNarrationFailure} from './notebooklm-narration-recovery.mjs';
const nb='16bc39aa-13a5-491a-a6ee-753c2c82ae54', src='12345678-1234-1234-1234-123456789abc', art='87654321-4321-4321-4321-cba987654321';
const post={slug:'best-workout-split',title:'Best Workout Split',url:'https://youraicoach.life/blog/best-workout-split'};
const env={GITHUB_RUN_ID:'37555071131',GITHUB_RUN_ATTEMPT:'5'};
async function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'izem-audio-test-'));fs.mkdirSync(path.join(root,'data/marketing-employee'),{recursive:true});fs.writeFileSync(path.join(root,'data/marketing-employee/video-repair-request.json'),JSON.stringify({slug:post.slug,recoverNotebookId:nb,recoverNarration:true,narrationWorkflowRunId:env.GITHUB_RUN_ID,narrationWorkflowRunAttempt:env.GITHUB_RUN_ATTEMPT}));try{await fn(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
function runner(options={}){const calls=[];let generated=false;return{calls,run:async(cmd,args)=>{calls.push(args);let out={};if(args[0]==='use')out={verified:options.verified!==false,notebook:{id:nb,title:`IZEM Video - ${post.title} - attempt 1`}};else if(args[0]==='source')out={sources:[{id:src,title:`${post.title} - canonical article`,status:options.sourceStatus||'ready'}]};else if(args[0]==='usage')out={is_exhausted:!!options.quota,actions:[{kind:'audio_overview',has_sufficient_quota:!options.quota}]};else if(args[0]==='artifact'&&args[1]==='list')out={artifacts:options.existing|| (generated?[{id:art,status:'completed'}]:[])};else if(args[0]==='generate'){if(options.failure||options.waitFails)throw{stdout:JSON.stringify({error:true,code:'QUOTA_EXCEEDED',message:'private secret'})};generated=true;out={task_id:art,status:'pending'};}else if(args[0]==='artifact'&&args[1]==='wait'){if(options.waitFails)throw{stdout:JSON.stringify({error:true,code:'GENERATION_FAILED',message:'private secret'})};out={status:'completed'};}else if(args[0]==='download'){assert.equal(args[1],'audio');assert.equal(args[args.indexOf('-a')+1],art);fs.writeFileSync(args[2],Buffer.alloc(11000));out={status:'success'};}else throw Error('unexpected command');return{stdout:JSON.stringify(out)};}};}
test('one source-scoped narration, exact download identity, never uploads',async()=>fixture(async root=>{const r=runner(),logs=[];const result=await recoverRequestedNarration(root,post,env,r.run,s=>logs.push(s));assert.equal(r.calls.filter(a=>a[0]==='generate').length,1);const gen=r.calls.find(a=>a[0]==='generate');assert.equal(gen[1],'audio');assert.equal(gen[gen.indexOf('-s')+1],src);assert.ok(!r.calls.some(a=>['create','delete','upload'].includes(a[0])));assert.equal(result.notebookId,nb);assert.equal(result.narrationArtifactId,art);assert.ok(!logs.join('').includes('private secret'));fs.rmSync(path.dirname(result.outputFile),{recursive:true,force:true});}));
test('completed narration reused after authorized attempt with no generation',async()=>fixture(async root=>{const r=runner({existing:[{id:art,status:'completed'}]});const result=await recoverRequestedNarration(root,post,{...env,GITHUB_RUN_ATTEMPT:'99'},r.run,()=>{});assert.equal(r.calls.filter(a=>a[0]==='generate').length,0);fs.rmSync(path.dirname(result.outputFile),{recursive:true,force:true});}));
test('wrong run cannot generate absent narration',async()=>fixture(async root=>{const r=runner();await assert.rejects(()=>recoverRequestedNarration(root,post,{...env,GITHUB_RUN_ID:'x'},r.run,()=>{}),/not authorized/);assert.ok(!r.calls.some(a=>a[0]==='generate'));}));
for(const options of [{quota:true},{verified:false},{sourceStatus:'processing'},{existing:[{id:art,status:'failed'}]},{existing:[{id:art,status:'pending'}]},{existing:[{id:art,status:'completed'},{id:src,status:'completed'}]}])test(`precondition rejects ${JSON.stringify(options)}`,async()=>fixture(async root=>{const r=runner(options);await assert.rejects(()=>recoverRequestedNarration(root,post,env,r.run,()=>{}));assert.ok(!r.calls.some(a=>a[0]==='generate'));}));
for(const options of [{failure:true},{waitFails:true}])test(`provider failure stops without duplicate ${JSON.stringify(options)}`,async()=>fixture(async root=>{const r=runner(options);await assert.rejects(()=>recoverRequestedNarration(root,post,env,r.run,()=>{}),e=>!e.message.includes('private secret'));assert.equal(r.calls.filter(a=>a[0]==='generate').length,1);assert.ok(!r.calls.some(a=>a[0]==='download'));}));
test('fixed typed errors only; no broad NotebookLM substring misclassification',()=>{assert.equal(safeNarrationFailure({stdout:JSON.stringify({code:'GENERATION_FAILED',message:'secret'})}),'GENERATION_FAILED');assert.equal(safeNarrationFailure({message:'NotebookLM artifact secret'}),'PROVIDER_REQUEST_FAILED');assert.equal(safeNarrationFailure({stdout:JSON.stringify({code:'PRIVATE_SECRET'})}),'PROVIDER_REQUEST_FAILED');});
