import { motion } from 'framer-motion';
import { Bot, Utensils, ScanFace, MessageSquareWarning, Flame, ShieldCheck } from 'lucide-react';

const features = [
    { icon: Bot, title: "AI Workout Plans", desc: "Fully personalized workout programs generated by AI based on your goal, fitness level, available equipment, and schedule." },
    { icon: Utensils, title: "AI Meal Plans", desc: "Personalized nutrition plans with macros calculated for your body weight, goal, and dietary preferences. Regenerate any day instantly." },
    { icon: ScanFace, title: "Body & Food Scan", desc: "Optionally use your camera for body analysis or to scan food for instant nutritional info. Images are processed by AI and never stored." },
    { icon: MessageSquareWarning, title: "AI Chat Coach", desc: "Ask your personal AI fitness coach anything — form tips, injury advice, motivation, or plan adjustments. Available 24/7." },
    { icon: Flame, title: "Streak & Progress Tracking", desc: "Build powerful consistency with daily streak tracking, total workout counts, and motivational milestone notifications." },
    { icon: ShieldCheck, title: "Private & Secure", desc: "Your data is encrypted. Body images are never stored. We never sell your personal data to third parties. Ever." },
];

export default function Features() {
    return (
        <section id="features" className="py-[100px] px-6">
            <div className="max-w-7xl mx-auto w-full">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                >
                    <div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[1.5px] text-primary mb-4 font-sans">
                        ✦ Core Features
                    </div>
                    <h2 className="text-4xl md:text-5xl font-extrabold font-condensed leading-[1.15] tracking-tight">
                        Everything you need.<br />Nothing you don't.
                    </h2>
                </motion.div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 mt-14">
                    {features.map((feat, idx) => {
                        const Icon = feat.icon;
                        return (
                            <motion.div
                                key={idx}
                                initial={{ opacity: 0, y: 30 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true, margin: "-50px" }}
                                transition={{ duration: 0.4, delay: idx * 0.1 }}
                                className="glass-card rounded-[24px] p-7 transition-all duration-300 hover:bg-primary/5 hover:border-primary/20 hover:-translate-y-1 hover:shadow-[0_20px_40px_rgba(0,0,0,0.3)] group cursor-pointer"
                            >
                                <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors duration-300">
                                    <Icon className="text-primary" size={24} strokeWidth={1.5} />
                                </div>
                                <h3 className="text-[17px] font-bold mb-2 font-sans text-textPrimary">{feat.title}</h3>
                                <p className="text-sm text-textSecondary leading-[1.65] font-sans">
                                    {feat.desc}
                                </p>
                            </motion.div>
                        );
                    })}
                </div>
            </div>
        </section>
    );
}
