import { motion } from 'framer-motion';
import { Bot, Utensils, ScanFace, MessageSquareWarning, Flame, ShieldCheck } from 'lucide-react';

export default function Features() {
    return (
        <section id="features" className="py-[120px] px-6 relative overflow-hidden">
            {/* Background decorations */}
            <div className="absolute top-1/4 left-0 w-1/3 h-1/2 bg-primary/5 blur-[120px] rounded-full pointer-events-none" />
            <div className="absolute bottom-0 right-0 w-1/4 h-1/3 bg-secondary/5 blur-[100px] rounded-full pointer-events-none" />

            <div className="max-w-7xl mx-auto w-full relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                    className="mb-16"
                >
                    <div className="inline-flex items-center gap-3 bg-white/5 border border-white/10 rounded-full px-4 py-2 text-[12px] text-primary font-bold uppercase tracking-[2px] mb-6 backdrop-blur-md">
                        ✦ Core Capabilities
                    </div>
                    <h2 className="text-5xl md:text-7xl font-extrabold font-condensed leading-[1.05] tracking-tighter">
                        PRO-GRADE TOOLKIT.<br />
                        <span className="text-textSecondary">ZERO FLUFF.</span>
                    </h2>
                </motion.div>

                {/* Bento Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[300px]">

                    {/* 1. Large Feature - AI Workout */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5 }}
                        className="md:col-span-2 md:row-span-2 bg-[#0C1232]/80 border border-white/10 rounded-[32px] p-10 relative overflow-hidden group hover:border-primary/40 transition-all duration-500 hover:shadow-[0_20px_60px_rgba(0,212,255,0.15)] flex flex-col justify-end"
                    >
                        {/* Peeking Image Visual */}
                        <div className="absolute -right-10 top-20 w-[240px] h-[520px] rounded-[36px] bg-black border-4 border-white/10 overflow-hidden shadow-2xl rotate-[8deg] group-hover:rotate-[4deg] group-hover:-translate-x-6 group-hover:scale-105 transition-all duration-700 hidden sm:block z-0 opacity-90 group-hover:opacity-100">
                            <img src="/images/hero1.png" alt="Workout Generator Interface" className="w-full h-full object-cover" loading="lazy" decoding="async" />
                            {/* Image Gradient Overlay for blending */}
                            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                        </div>

                        <div className="absolute inset-0 bg-gradient-to-r from-[#0C1232] via-[#0C1232]/90 to-transparent sm:w-[70%] z-0" />
                        <div className="absolute -top-32 -left-32 w-80 h-80 bg-gradient-to-br from-primary/20 to-transparent blur-3xl rounded-full group-hover:scale-110 transition-transform duration-700" />

                        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center mb-6 relative z-10 shadow-lg shadow-primary/20">
                            <Bot className="text-white" size={28} />
                        </div>
                        <h3 className="text-4xl font-black font-condensed tracking-tight mb-3 relative z-10 text-white">Intelligent Workout Generation</h3>
                        <p className="text-base text-textSecondary leading-relaxed max-w-sm relative z-10 font-light">
                            Fully personalized workout programs generated by advanced AI. Tailored directly to your current fitness level, mechanical goals, available equipment, and weekly schedule constraints.
                        </p>
                    </motion.div>

                    {/* 2. Small Feature - AI Meal */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.1 }}
                        className="bg-[#0C1232]/80 border border-white/10 rounded-[32px] p-8 relative overflow-hidden group hover:bg-[#131A42]/90 transition-all duration-300"
                    >
                        {/* Visual: Macro Ring Chart */}
                        <div className="absolute top-8 right-8 w-16 h-16 rounded-full border-[6px] border-white/5 border-t-secondary border-r-primary rotate-45 group-hover:rotate-[225deg] transition-all duration-700 opacity-40 z-0"></div>

                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:bg-secondary/20 group-hover:text-secondary group-hover:border-secondary/30 transition-all duration-300 relative z-10">
                            <Utensils className="text-textSecondary group-hover:text-secondary transition-colors" size={24} />
                        </div>
                        <h3 className="text-[22px] font-bold font-condensed mb-2 relative z-10 text-white">Macro-Aligned Meals</h3>
                        <p className="text-[14px] text-textSecondary leading-relaxed font-light relative z-10">
                            Nutrition blueprints precisely calculated for your exact basal metabolic rate. Regenerate anytime.
                        </p>
                    </motion.div>

                    {/* 3. Small Feature - Scan */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.2 }}
                        className="bg-[#0C1232]/80 border border-white/10 rounded-[32px] p-8 relative overflow-hidden group hover:bg-[#131A42]/90 transition-all duration-300"
                    >
                        {/* Visual: Scanning Laser */}
                        <div className="absolute top-1/2 right-6 w-20 h-20 border border-white/5 rounded-lg opacity-40 overflow-hidden flex items-center justify-center z-0">
                            <ScanFace size={40} className="text-white/10" />
                            <div className="absolute inset-0 bg-gradient-to-b from-transparent via-primary/40 to-transparent h-1.5 w-full -translate-y-10 group-hover:animate-[scan_2s_ease-in-out_infinite]" />
                        </div>

                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:bg-primary/20 group-hover:text-primary group-hover:border-primary/30 transition-all duration-300 relative z-10">
                            <ScanFace className="text-textSecondary group-hover:text-primary transition-colors" size={24} />
                        </div>
                        <h3 className="text-[22px] font-bold font-condensed mb-2 relative z-10 text-white">Visual Biometrics</h3>
                        <p className="text-[14px] text-textSecondary leading-relaxed font-light relative z-10">
                            Upload photos for instant posture analysis and nutritional scanning. Privately processed, never stored.
                        </p>
                    </motion.div>

                    {/* 4. Small Feature - Chat */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.3 }}
                        className="bg-[#0C1232]/80 border border-white/10 rounded-[32px] p-8 relative overflow-hidden group hover:bg-[#131A42]/90 transition-all duration-300"
                    >
                        {/* Visual: Chat Bubbles */}
                        <div className="absolute top-8 right-8 flex flex-col gap-2 opacity-30 group-hover:opacity-60 transition-opacity z-0">
                            <div className="w-16 h-6 bg-white/10 rounded-full rounded-br-sm self-end group-hover:-translate-x-1 group-hover:-translate-y-1 transition-transform duration-500" />
                            <div className="w-20 h-6 bg-primary/20 rounded-full rounded-bl-sm group-hover:translate-x-1 group-hover:translate-y-1 transition-transform duration-500" />
                        </div>

                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:bg-white/20 group-hover:border-white/30 transition-all duration-300 relative z-10">
                            <MessageSquareWarning className="text-textSecondary group-hover:text-white transition-colors" size={24} />
                        </div>
                        <h3 className="text-[22px] font-bold font-condensed mb-2 relative z-10 text-white">24/7 AI Coach</h3>
                        <p className="text-[14px] text-textSecondary leading-relaxed font-light relative z-10">
                            Instant form checks, injury modification advice, and real-time motivational chats whenever you need it.
                        </p>
                    </motion.div>

                    {/* 5. Medium Feature - Streak (Spans 2 columns, short row) */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.4 }}
                        className="md:col-span-2 bg-[#0C1232]/80 border border-white/10 rounded-[32px] p-8 relative overflow-hidden group hover:border-cta/40 transition-all duration-500"
                    >
                        {/* Ambient Glow */}
                        <div className="absolute inset-0 bg-gradient-to-br from-cta/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-0" />

                        {/* Peeking Image Visual on the far right */}
                        <div className="absolute -right-20 -bottom-32 w-[260px] h-[360px] rounded-[36px] bg-black border-4 border-white/10 overflow-hidden shadow-2xl -rotate-[10deg] group-hover:-rotate-[5deg] group-hover:-translate-y-4 group-hover:scale-105 transition-all duration-700 hidden sm:block z-0 opacity-80 group-hover:opacity-100">
                            <img src="/images/hero2.png" alt="Streak Dashboard" className="w-full h-full object-cover object-top" loading="lazy" decoding="async" />
                        </div>

                        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6 h-full relative z-10 sm:max-w-[50%]">
                            <div className="w-20 h-20 shrink-0 rounded-2xl bg-gradient-to-br from-cta/20 to-cta/5 border border-cta/30 flex items-center justify-center shadow-[0_0_20px_rgba(34,197,94,0.15)] group-hover:scale-110 transition-transform duration-500">
                                <Flame className="text-cta" size={36} fill="currentColor" />
                            </div>
                            <div>
                                <h3 className="text-3xl font-bold font-condensed mb-2 text-white">Unbreakable Tracking</h3>
                                <p className="text-[15px] text-textSecondary leading-relaxed font-light">
                                    Gamified streak tracking, lifetime volume analytics, and adaptive notifications.
                                </p>
                            </div>
                        </div>
                    </motion.div>

                    {/* 6. Wide Feature - Privacy (Full Width Row) */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.98 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.5 }}
                        className="md:col-span-3 rounded-[32px] p-[1px] bg-gradient-to-r from-bgPrimary via-white/20 to-bgPrimary overflow-hidden"
                    >
                        <div className="w-full h-full bg-[#0C1232] rounded-[31px] p-6 sm:p-8 flex flex-col md:flex-row items-center gap-6 md:gap-10 justify-between group hover:bg-gradient-to-r hover:from-[#131A42] hover:to-[#0C1232] transition-colors duration-500">
                            <div className="flex items-center gap-6">
                                <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center border border-white/10 shrink-0 group-hover:bg-white/10 transition-colors duration-300">
                                    <ShieldCheck size={28} className="text-white" />
                                </div>
                                <div>
                                    <h3 className="text-[22px] font-bold font-condensed mb-1 text-white">Military-Grade Privacy</h3>
                                    <p className="text-sm text-textSecondary font-light">End-to-end encryption. No data selling. Instant account deletion inside the app.</p>
                                </div>
                            </div>
                            <a href="#data" className="px-8 py-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white text-textSecondary hover:text-black text-[13px] font-bold uppercase tracking-wider transition-all duration-300 whitespace-nowrap">
                                Read Our Policy
                            </a>
                        </div>
                    </motion.div>

                </div>
            </div>

            {/* CSS Animation for scanning line */}
            <style>{`
        @keyframes scan {
          0% { transform: translateY(-10px); opacity: 0; }
          10% { opacity: 1; }
          90% { opacity: 1; }
          100% { transform: translateY(40px); opacity: 0; }
        }
      `}</style>
        </section>
    );
}
