import { motion } from 'framer-motion';
import { Bot, Utensils, ScanFace, MessageSquareWarning, Flame, ShieldCheck } from 'lucide-react';

export default function Features() {
    return (
        <section id="features" className="py-[120px] px-6 relative">
            {/* Background decorations */}
            <div className="absolute top-1/4 left-0 w-1/3 h-1/2 bg-primary/5 blur-[120px] rounded-full pointer-events-none" />
            <div className="absolute bottom-0 right-0 w-1/4 h-1/3 bg-secondary/5 blur-[100px] rounded-full pointer-events-none" />

            <div className="max-w-7xl mx-auto w-full relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                    className="mb-16"
                >
                    <div className="inline-flex items-center gap-3 bg-white/5 border border-white/10 rounded-full px-4 py-2 text-[12px] text-primary font-bold uppercase tracking-[2px] mb-6 backdrop-blur-md">
                        ✦ Core Capabilities
                    </div>
                    <h2 className="text-5xl md:text-7xl font-extrabold font-condensed leading-[1.05] tracking-tighter">
                        PRO-GRADE TOOLKIT.<br />
                        <span className="text-textSecondary">ZERO FLUFF.</span>
                    </h2>
                </motion.div>

                {/* Bento Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[250px]">

                    {/* 1. Large Feature - AI Workout */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5 }}
                        className="md:col-span-2 md:row-span-2 glass-card rounded-[32px] p-10 relative overflow-hidden group hover:border-primary/30 transition-all duration-500 hover:shadow-[0_20px_50px_rgba(0,180,255,0.15)] flex flex-col justify-end"
                    >
                        <div className="absolute -top-32 -right-32 w-80 h-80 bg-gradient-to-br from-primary/20 to-transparent blur-3xl rounded-full group-hover:scale-110 transition-transform duration-700" />

                        <div className="absolute top-10 right-10 w-48 h-48 border-[1px] border-white/10 rounded-full flex items-center justify-center translate-x-10 -translate-y-10 group-hover:translate-x-0 transition-transform duration-700 opacity-20">
                            <div className="w-32 h-32 border-[1px] border-white/20 rounded-full flex items-center justify-center">
                                <div className="w-16 h-16 border-[1px] border-primary/40 rounded-full" />
                            </div>
                        </div>

                        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center mb-6 relative z-10 shadow-lg shadow-primary/20">
                            <Bot className="text-white" size={28} />
                        </div>
                        <h3 className="text-3xl font-black font-condensed tracking-tight mb-3 relative z-10">Intelligent Workout Generation</h3>
                        <p className="text-base text-textSecondary leading-relaxed max-w-md relative z-10 font-light">
                            Fully personalized workout programs generated by advanced AI. Tailored directly to your current fitness level, mechanical goals, available equipment, and weekly schedule constraints.
                        </p>
                    </motion.div>

                    {/* 2. Small Feature - AI Meal */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.1 }}
                        className="glass-card rounded-[32px] p-8 relative overflow-hidden group hover:bg-white/[0.08] transition-all duration-300"
                    >
                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:bg-secondary/20 group-hover:text-secondary transition-colors duration-300">
                            <Utensils className="text-textSecondary group-hover:text-secondary transition-colors" size={24} />
                        </div>
                        <h3 className="text-[22px] font-bold font-condensed mb-2">Macro-Aligned Meals</h3>
                        <p className="text-[14px] text-textSecondary leading-relaxed font-light">
                            Nutrition blueprints precisely calculated for your exact basal metabolic rate. Regenerate anytime.
                        </p>
                    </motion.div>

                    {/* 3. Small Feature - Scan */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.2 }}
                        className="glass-card rounded-[32px] p-8 relative overflow-hidden group hover:bg-white/[0.08] transition-all duration-300"
                    >
                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:bg-primary/20 group-hover:text-primary transition-colors duration-300">
                            <ScanFace className="text-textSecondary group-hover:text-primary transition-colors" size={24} />
                        </div>
                        <h3 className="text-[22px] font-bold font-condensed mb-2">Visual Biometrics</h3>
                        <p className="text-[14px] text-textSecondary leading-relaxed font-light">
                            Upload photos for instant posture analysis and nutritional scanning. Privately processed, never stored.
                        </p>
                    </motion.div>

                    {/* 4. Small Feature - Chat */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.3 }}
                        className="glass-card rounded-[32px] p-8 relative overflow-hidden group hover:bg-white/[0.08] transition-all duration-300"
                    >
                        <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 group-hover:bg-white/20 transition-colors duration-300">
                            <MessageSquareWarning className="text-textSecondary group-hover:text-white transition-colors" size={24} />
                        </div>
                        <h3 className="text-[22px] font-bold font-condensed mb-2">24/7 AI Coach</h3>
                        <p className="text-[14px] text-textSecondary leading-relaxed font-light">
                            Instant form checks, injury modification advice, and real-time motivational chats whenever you need it.
                        </p>
                    </motion.div>

                    {/* 5. Medium Feature - Streak */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.4 }}
                        className="md:col-span-2 glass-card rounded-[32px] p-8 relative overflow-hidden group hover:border-cta/30 transition-all duration-500 bg-gradient-to-r hover:from-cta/5 hover:to-transparent"
                    >
                        <div className="flex items-center gap-6 h-full">
                            <div className="w-20 h-20 shrink-0 rounded-full bg-cta/10 border border-cta/20 flex items-center justify-center shadow-[0_0_20px_rgba(34,197,94,0.15)] group-hover:scale-110 transition-transform duration-500">
                                <Flame className="text-cta" size={36} fill="currentColor" />
                            </div>
                            <div>
                                <h3 className="text-2xl font-bold font-condensed mb-2 text-white">Unbreakable Consistency Tracking</h3>
                                <p className="text-[15px] text-textSecondary leading-relaxed font-light max-w-sm">
                                    Gamified streak tracking, lifetime volume analytics, and adaptive milestone notifications to keep you locked in.
                                </p>
                            </div>
                        </div>
                    </motion.div>

                    {/* 6. Wide Feature - Privacy */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.98 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: 0.5 }}
                        className="md:col-span-3 rounded-[32px] p-[2px] bg-gradient-to-r from-bgPrimary via-white/10 to-bgPrimary overflow-hidden"
                    >
                        <div className="w-full h-full bg-bgPrimary rounded-[30px] p-8 flex flex-col md:flex-row items-center gap-6 md:gap-10 justify-between">
                            <div className="flex items-center gap-6">
                                <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center border border-white/10 shrink-0">
                                    <ShieldCheck size={28} className="text-textSecondary" />
                                </div>
                                <div>
                                    <h3 className="text-[22px] font-bold font-condensed mb-1">Military-Grade Privacy</h3>
                                    <p className="text-sm text-textSecondary font-light">End-to-end encryption. No data selling. Instant account deletion.</p>
                                </div>
                            </div>
                            <a href="#data" className="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/20 text-sm font-semibold transition-colors whitespace-nowrap">
                                Read Our Policy
                            </a>
                        </div>
                    </motion.div>

                </div>
            </div>
        </section>
    );
}
