import { motion } from 'framer-motion';

const steps = [
    {
        num: "1",
        title: "Complete Your Profile",
        desc: "Tell us about your goals, fitness level, body metrics, dietary preferences and any injuries. Our AI builds your complete picture."
    },
    {
        num: "2",
        title: "Get Your AI Plans",
        desc: "Instantly receive a personalized workout plan AND a meal plan generated by AI — tailored specifically to your body and goals."
    },
    {
        num: "3",
        title: "Train & Track Progress",
        desc: "Follow your plan, scan food for nutrition analysis, chat with your AI coach, and build unbreakable consistency with streak tracking."
    }
];

export default function HowItWorks() {
    return (
        <section id="how" className="py-[100px] px-6 bg-gradient-to-b from-transparent via-[#0C1232]/50 to-transparent relative">
            <div className="max-w-7xl mx-auto w-full">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                >
                    <div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[1.5px] text-primary mb-4 font-sans">
                        ✦ Simple Process
                    </div>
                    <h2 className="text-4xl md:text-5xl font-extrabold font-condensed leading-[1.15] tracking-tight mb-4">
                        Three steps to your<br />strongest self
                    </h2>
                    <p className="text-[17px] text-textSecondary max-w-[560px] leading-relaxed font-sans">
                        No guesswork. No generic plans. Pure AI-powered precision built around you.
                    </p>
                </motion.div>

                <div className="grid md:grid-cols-3 gap-6 mt-14 relative">
                    {steps.map((step, idx) => (
                        <motion.div
                            key={idx}
                            initial={{ opacity: 0, y: 30 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true, margin: "-50px" }}
                            transition={{ duration: 0.5, delay: idx * 0.15 }}
                            className="glass-card rounded-[24px] p-9 relative group hover:border-primary/25 hover:-translate-y-1 transition-all duration-300"
                        >
                            <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center font-extrabold text-lg text-white mb-5 shadow-lg shadow-primary/20">
                                {step.num}
                            </div>
                            <h3 className="text-[19px] font-bold mb-2.5 font-sans text-textPrimary">{step.title}</h3>
                            <p className="text-sm text-textSecondary leading-[1.65] font-sans">
                                {step.desc}
                            </p>

                            {/* Connector */}
                            {idx < steps.length - 1 && (
                                <div className="hidden md:flex absolute top-1/2 -right-[13px] -translate-y-1/2 w-[26px] h-[26px] bg-bgPrimary border border-glassBorder rounded-full flex items-center justify-center text-xs z-10 text-textSecondary">
                                    →
                                </div>
                            )}
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
}
