import { readdir, readFile } from 'node:fs/promises'
import path from 'node:path'

import { load } from 'cheerio'

const siteOrigin = 'https://youraicoach.life'
const distDirectory = path.resolve('dist')
const excludedDirectory = 'blog/drafts/'
const videoSitemapFile = 'video-sitemap.xml'
const knownDeadUrls = [
  'https://apps.apple.com/app/your-ai-coach',
  'https://play.google.com/store/apps/details?id=com.ai.gym.coach',
  'https://health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines/current-guidelines/adults',
]

async function collectFiles(directory, relativeDirectory = '') {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = []

  for (const entry of entries) {
    const relativePath = path.posix.join(relativeDirectory, entry.name)
    const absolutePath = path.join(directory, entry.name)

    if (entry.isDirectory()) {
      files.push(...(await collectFiles(absolutePath, relativePath)))
    } else {
      files.push(relativePath)
    }
  }

  return files
}

function pageUrl(relativeFile) {
  if (relativeFile === 'index.html') return `${siteOrigin}/`
  if (relativeFile.endsWith('/index.html')) {
    return `${siteOrigin}/${relativeFile.slice(0, -'index.html'.length)}`
  }
  return `${siteOrigin}/${relativeFile}`
}

function candidateFiles(pathname) {
  let decodedPath

  try {
    decodedPath = decodeURIComponent(pathname)
  } catch {
    decodedPath = pathname
  }

  const relativePath = decodedPath.replace(/^\/+/, '')
  if (!relativePath || decodedPath.endsWith('/')) {
    return [path.posix.join(relativePath, 'index.html')]
  }

  return [relativePath, `${relativePath}.html`, path.posix.join(relativePath, 'index.html')]
}

function resolveInternalUrl(href, sourceFile) {
  const normalizedHref = href.trim()
  if (
    !normalizedHref ||
    normalizedHref.startsWith('#') ||
    /^(?:mailto|tel|javascript|data):/i.test(normalizedHref)
  ) {
    return null
  }

  const url = new URL(normalizedHref, pageUrl(sourceFile))
  if (url.origin !== siteOrigin) return null
  return url
}

function targetExists(url, allFiles) {
  return candidateFiles(url.pathname).some((candidate) => allFiles.has(candidate))
}

function targetFile(url, allFiles) {
  return candidateFiles(url.pathname).find((candidate) => allFiles.has(candidate))
}

function normalizedIndexUrl(value) {
  const url = value instanceof URL ? value : new URL(value)
  const pathname = url.pathname === '/' ? '/' : url.pathname.replace(/\/+$/, '')
  return `${url.origin}${pathname}${url.search}`
}

const files = await collectFiles(distDirectory)
const allFiles = new Set(files)
const htmlFiles = files.filter(
  (file) => file.endsWith('.html') && !file.startsWith(excludedDirectory),
)
const errors = []
let checkedLinks = 0
const sitemapCanonicalUrls = new Set()
const videoSitemapUrls = new Set()

function typedJsonLdItems(value, type, items = []) {
  if (Array.isArray(value)) {
    for (const item of value) typedJsonLdItems(item, type, items)
  } else if (value && typeof value === 'object') {
    const itemType = value['@type']
    if (itemType === type || (Array.isArray(itemType) && itemType.includes(type))) items.push(value)
    for (const child of Object.values(value)) typedJsonLdItems(child, type, items)
  }
  return items
}

for (const htmlFile of htmlFiles) {
  const html = await readFile(path.join(distDirectory, htmlFile), 'utf8')

  for (const deadUrl of knownDeadUrls) {
    if (html.includes(deadUrl)) {
      errors.push(`${htmlFile}: contains known 404 URL ${deadUrl}`)
    }
  }

  const $ = load(html)

  const videoFrames = $('iframe[src*="youtube.com/embed/"]')
  const isWatchPage = /^youtube\/[^/]+\/index\.html$/.test(htmlFile)
  if (isWatchPage) {
    const videoId = htmlFile.split('/')[1]
    if (!html.includes('Generated by tools/sync-video-pages.mjs')) {
      errors.push(`${htmlFile}: dedicated watch page is not generated by the video sync tool`)
    }
    if (videoFrames.length !== 1) {
      errors.push(`${htmlFile}: dedicated watch page must have exactly one video iframe (found ${videoFrames.length})`)
    } else {
      const embedUrl = videoFrames.attr('src') || ''
      if (!embedUrl.includes(`/embed/${videoId}`)) {
        errors.push(`${htmlFile}: iframe ${embedUrl} does not match watch-page video ${videoId}`)
      }
    }
    if ($('main [data-primary-video="true"] iframe').length !== 1) {
      errors.push(`${htmlFile}: video must be the primary content inside main`)
    }

    const videoObjects = []
    for (const element of $('script[type="application/ld+json"]').toArray()) {
      try {
        typedJsonLdItems(JSON.parse($(element).text()), 'VideoObject', videoObjects)
      } catch {
        // The general JSON-LD validation below reports the parse error.
      }
    }
    if (videoObjects.length !== 1) {
      errors.push(`${htmlFile}: expected exactly one VideoObject (found ${videoObjects.length})`)
    } else {
      const video = videoObjects[0]
      for (const required of ['name', 'description', 'thumbnailUrl', 'uploadDate', 'embedUrl']) {
        if (!video[required]) errors.push(`${htmlFile}: VideoObject is missing ${required}`)
      }
      if (!String(video.embedUrl || '').includes(`/embed/${videoId}`)) {
        errors.push(`${htmlFile}: VideoObject embedUrl does not match ${videoId}`)
      }
    }
  } else if (videoFrames.length > 0) {
    errors.push(`${htmlFile}: embedded video must live on a dedicated /youtube/{id}/ watch page`)
  }

  for (const card of $('[data-izem-video-card="true"][data-video-id]').toArray()) {
    const videoId = $(card).attr('data-video-id')
    const href = $(card).attr('href')
    if (href !== `/youtube/${videoId}/`) {
      errors.push(`${htmlFile}: video card ${videoId} must link to /youtube/${videoId}/`)
    }
  }

  for (const element of $('a[href]').toArray()) {
    const href = $(element).attr('href')
    if (!href) continue

    let url
    try {
      url = resolveInternalUrl(href, htmlFile)
    } catch {
      errors.push(`${htmlFile}: invalid href ${href}`)
      continue
    }

    if (!url) continue
    checkedLinks += 1

    if (!targetExists(url, allFiles)) {
      errors.push(`${htmlFile}: ${href} has no built target`)
    }
  }
}

if (!allFiles.has(videoSitemapFile)) {
  errors.push(`${videoSitemapFile}: missing generated video sitemap`)
} else {
  const videoSitemap = await readFile(path.join(distDirectory, videoSitemapFile), 'utf8')
  const entries = [...videoSitemap.matchAll(/<url>\s*([\s\S]*?)\s*<\/url>/g)].map((match) => match[1])

  for (const entry of entries) {
    const location = entry.match(/<loc>([^<]+)<\/loc>/)?.[1]?.trim()
    const playerLocation = entry.match(/<video:player_loc\b[^>]*>([^<]+)<\/video:player_loc>/)?.[1]?.trim()
    if (!location) {
      errors.push(`${videoSitemapFile}: entry is missing loc`)
      continue
    }

    const normalizedLocation = normalizedIndexUrl(location)
    if (videoSitemapUrls.has(normalizedLocation)) {
      errors.push(`${videoSitemapFile}: duplicate watch page ${location}`)
    }
    videoSitemapUrls.add(normalizedLocation)

    const match = new URL(location).pathname.match(/^\/youtube\/([^/]+)\/?$/)
    const videoId = match?.[1]
    if (!videoId) errors.push(`${videoSitemapFile}: ${location} is not a dedicated watch page`)
    if (!playerLocation || !playerLocation.includes(`/embed/${videoId}`)) {
      errors.push(`${videoSitemapFile}: ${location} has a missing or mismatched player_loc`)
    }
    for (const requiredTag of ['video:thumbnail_loc', 'video:title', 'video:description', 'video:publication_date']) {
      if (!entry.includes(`<${requiredTag}>`)) errors.push(`${videoSitemapFile}: ${location} is missing ${requiredTag}`)
    }
    if (!targetExists(new URL(location), allFiles)) {
      errors.push(`${videoSitemapFile}: ${location} has no built watch page`)
    }
  }

  const watchPages = htmlFiles.filter((file) => /^youtube\/[^/]+\/index\.html$/.test(file))
  for (const watchPage of watchPages) {
    const videoId = watchPage.split('/')[1]
    const location = normalizedIndexUrl(`${siteOrigin}/youtube/${videoId}/`)
    if (!videoSitemapUrls.has(location)) {
      errors.push(`${watchPage}: dedicated watch page is missing from ${videoSitemapFile}`)
    }
  }
}

const sitemapFile = 'sitemap.xml'
if (allFiles.has(sitemapFile)) {
  const sitemap = await readFile(path.join(distDirectory, sitemapFile), 'utf8')
  const locations = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1].trim())
  const seenLocations = new Set()

  for (const location of locations) {
    let url
    try {
      url = new URL(location)
    } catch {
      errors.push(`${sitemapFile}: invalid URL ${location}`)
      continue
    }

    if (seenLocations.has(normalizedIndexUrl(url))) {
      errors.push(`${sitemapFile}: duplicate URL ${location}`)
    }
    seenLocations.add(normalizedIndexUrl(url))
    sitemapCanonicalUrls.add(normalizedIndexUrl(url))

    if (url.origin !== siteOrigin) continue

    const relativeFile = targetFile(url, allFiles)
    if (!relativeFile) {
      errors.push(`${sitemapFile}: ${location} has no built target`)
      continue
    }

    if (!relativeFile.endsWith('.html')) continue

    const html = await readFile(path.join(distDirectory, relativeFile), 'utf8')
    const $ = load(html)
    const canonicalLinks = $('link[rel="canonical"]')

    if (canonicalLinks.length !== 1) {
      errors.push(`${relativeFile}: sitemap page must have exactly one canonical (found ${canonicalLinks.length})`)
    } else {
      const canonicalHref = canonicalLinks.attr('href')
      try {
        const canonicalUrl = new URL(canonicalHref, url)
        if (normalizedIndexUrl(canonicalUrl) !== normalizedIndexUrl(url)) {
          errors.push(`${relativeFile}: canonical ${canonicalUrl.href} does not match sitemap URL ${location}`)
        }
      } catch {
        errors.push(`${relativeFile}: invalid canonical ${canonicalHref}`)
      }
    }

    const robotsContents = $('meta')
      .toArray()
      .filter((element) => ($(element).attr('name') || '').toLowerCase() === 'robots')
      .map((element) => $(element).attr('content') || '')
    if (robotsContents.some((content) => /(?:^|,)\s*noindex(?:\s|,|$)/i.test(content))) {
      errors.push(`${relativeFile}: sitemap page is marked noindex`)
    }

    for (const element of $('script[type="application/ld+json"]').toArray()) {
      const json = $(element).text().trim()
      if (!json) continue
      try {
        JSON.parse(json)
      } catch (error) {
        errors.push(`${relativeFile}: invalid JSON-LD (${error.message})`)
      }
    }
  }
}

for (const videoLocation of videoSitemapUrls) {
  if (!sitemapCanonicalUrls.has(videoLocation)) {
    errors.push(`${videoSitemapFile}: ${videoLocation} is missing from sitemap.xml`)
  }
}

const newsSitemapFile = 'news-sitemap.xml'
if (allFiles.has(newsSitemapFile)) {
  const newsSitemap = await readFile(path.join(distDirectory, newsSitemapFile), 'utf8')
  for (const location of [...newsSitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1].trim())) {
    let url
    try {
      url = new URL(location)
    } catch {
      errors.push(`${newsSitemapFile}: invalid URL ${location}`)
      continue
    }
    if (!targetExists(url, allFiles)) errors.push(`${newsSitemapFile}: ${location} has no built target`)
    if (!sitemapCanonicalUrls.has(normalizedIndexUrl(url))) {
      errors.push(`${newsSitemapFile}: ${location} is missing from sitemap.xml`)
    }
  }
}

for (const htmlFile of htmlFiles) {
  const html = await readFile(path.join(distDirectory, htmlFile), 'utf8')
  const $ = load(html)
  const robotsContents = $('meta')
    .toArray()
    .filter((element) => ($(element).attr('name') || '').toLowerCase() === 'robots')
    .map((element) => $(element).attr('content') || '')

  if (robotsContents.some((content) => /(?:^|,)\s*noindex(?:\s|,|$)/i.test(content))) continue

  const canonicalLinks = $('link')
    .toArray()
    .filter((element) =>
      (($(element).attr('rel') || '').toLowerCase().split(/\s+/)).includes('canonical'),
    )

  if (canonicalLinks.length !== 1) {
    errors.push(`${htmlFile}: indexable page must have exactly one canonical (found ${canonicalLinks.length})`)
    continue
  }

  const canonicalHref = $(canonicalLinks[0]).attr('href')
  try {
    const canonicalUrl = new URL(canonicalHref, pageUrl(htmlFile))
    if (canonicalUrl.origin === siteOrigin && !sitemapCanonicalUrls.has(normalizedIndexUrl(canonicalUrl))) {
      errors.push(`${htmlFile}: indexable canonical ${canonicalUrl.href} is missing from sitemap.xml`)
    }
  } catch {
    errors.push(`${htmlFile}: invalid canonical ${canonicalHref}`)
  }
}

const canonicalPageAudits = new Map()
const inboundCanonicalLinks = new Map([...sitemapCanonicalUrls].map((url) => [url, 0]))

for (const htmlFile of htmlFiles) {
  const html = await readFile(path.join(distDirectory, htmlFile), 'utf8')
  const $ = load(html)
  const robots = $('meta[name="robots"]').attr('content') || ''
  if (/(?:^|,)\s*noindex(?:\s|,|$)/i.test(robots)) continue

  const canonicalHref = $('link[rel="canonical"]').attr('href')
  if (!canonicalHref) continue
  let canonicalUrl
  try {
    canonicalUrl = new URL(canonicalHref, pageUrl(htmlFile))
  } catch {
    continue
  }
  const canonical = normalizedIndexUrl(canonicalUrl)

  const title = $('title').text().trim()
  const description = $('meta[name="description"]').attr('content')?.trim() || ''
  const language = $('html').attr('lang')?.trim() || ''
  if (!title) errors.push(`${htmlFile}: indexable page is missing a title`)
  if (!description) errors.push(`${htmlFile}: indexable page is missing a meta description`)
  if (!language) errors.push(`${htmlFile}: indexable page is missing an html lang attribute`)
  if ($('h1').length !== 1) {
    errors.push(`${htmlFile}: indexable page must have exactly one h1 (found ${$('h1').length})`)
  }
  for (const image of $('img').toArray()) {
    if ($(image).attr('alt') === undefined) errors.push(`${htmlFile}: image is missing alt text`)
    if (!$(image).attr('width') || !$(image).attr('height')) {
      errors.push(`${htmlFile}: image ${$(image).attr('src') || '(unknown source)'} is missing width or height`)
    }
  }

  const target = targetFile(canonicalUrl, allFiles)
  const current = canonicalPageAudits.get(canonical)
  const audit = { htmlFile, title, description }
  if (!current || target === htmlFile) canonicalPageAudits.set(canonical, audit)

  for (const anchor of $('a[href]').toArray()) {
    const href = $(anchor).attr('href')
    if (!href) continue
    try {
      const url = resolveInternalUrl(href, htmlFile)
      if (!url) continue
      const destination = normalizedIndexUrl(url)
      if (destination !== canonical && inboundCanonicalLinks.has(destination)) {
        inboundCanonicalLinks.set(destination, inboundCanonicalLinks.get(destination) + 1)
      }
    } catch {
      // The general link validation above reports malformed href values.
    }
  }
}

for (const [canonical, inboundLinks] of inboundCanonicalLinks) {
  if (canonical !== siteOrigin && inboundLinks === 0) {
    errors.push(`${canonical}: sitemap page has no inbound internal link`)
  }
}

for (const field of ['title', 'description']) {
  const owners = new Map()
  for (const [canonical, page] of canonicalPageAudits) {
    if (!sitemapCanonicalUrls.has(canonical)) continue
    const key = page[field].toLowerCase()
    if (!key) continue
    const urls = owners.get(key) || []
    urls.push(canonical)
    owners.set(key, urls)
  }
  for (const [value, urls] of owners) {
    if (urls.length > 1) {
      errors.push(`duplicate ${field} on ${urls.join(', ')}: ${value.slice(0, 120)}`)
    }
  }
}

if (errors.length > 0) {
  console.error(`Link check failed with ${errors.length} error(s):`)
  for (const error of errors) console.error(`- ${error}`)
  process.exitCode = 1
} else {
  console.log(`Link check passed: ${htmlFiles.length} pages and ${checkedLinks} internal links checked.`)
}
